### ISSUE TITLE
Game does not understand gender.

### ISSUE THREAD

**Issue by MisterLayne** [PolarisSS13/Polaris#4632] opened 2018-01-25 03:19 UTC
#### Brief description of the issue
The game seems to not understand the gender of the person.

#### What you expected to happen
The game to get 'he' and 'she' right.

#### What actually happened
Apparently people are confused about their gender.

#### Steps to reproduce
I have no clue.

#### Additional info:
 - **Server Revision**: master - 2018-01-22
2692c924487955f91b8f485c1ee9e950fdc9dbc1 

![image](https://user-images.githubusercontent.com/31356648/35369128-95bb7f18-0154-11e8-9fea-bcc038cc6bfb.png)

**Comment by Atermonera** [comment] 2018-01-25 04:59
Presumably from the days where gender was used as a binary, and the /him macros were perfectly fine for use. I think there's some more modern var that should be used instead

**Comment by MarinaGryphon** [comment] 2018-01-30 04:55
This is because of some very hacky code. PR incoming. The issue is the lack of a `himself` variable on gender, which I'm going to add along with a fix for this.

**Closed** 2018-02-03 20:40 UTC
Labels: Oversight, Priority: Zero
