### ISSUE TITLE
Plastic flaps in disposals access are not airtight.

### ISSUE THREAD

**Issue by PapaDrow** [PolarisSS13/Polaris#1277] opened 2016-03-28 14:18 UTC
#### Brief description of the issue

Plastic flaps on disposals line (specifically, the area with the mass driver) are not of the 'airtight' variety.

#### What you expected to happen

For the conveyor line either to have no easy access (ie an airlock) or to have airtight flaps at the end. Or at least a warning sign.

#### What actually happened

Whenever the chute to the mass driver is activated and the mass driver itself is fired, there appears to be leakage of pressure in the section of disposals with the conveyor. If anyone opens the airlock onto the conveyor belt, it tends to depressurize the whole room for a moment and causes injury.

#### Steps to reproduce

Go to the disposals line via maint, activate both the conveyor (when there's something on it so the chute at the end activates) and then use the mass driver.

#### Additional info:
 - master - 2016-03-27 ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0

**Comment by Nerezza** [comment] 2016-03-28 17:35
Just to describe it in another way. The chute in disposals is pressurizing off ambient air, and it quickly sucks up the air inside the conveyor portion.

I'm not sure if it needs air to actually operate, if not then airtight flaps would work like Drow says. If it does need air, then that section of disposals needs a vent.

**Comment by Yoshax** [comment] 2016-04-28 16:23
Duplicate of #766

**Closed** 2016-06-01 01:28 UTC
Labels: Map Change / Issue
