### ISSUE TITLE
Hacking Tool Does Not Hack

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#7293] opened 2020-06-15 01:36 UTC
#### Brief description of the issue
The traitor uplink item multitool hacking tool does not open the hacking progress bar / interface when used on a door.

#### What you expected to happen
Use a screwdriver on the hacking multitool to engage Hack Mode. Click on door. Hack door.

#### What actually happened
Use a screwdriver on the hacking multitool to engage Hack Mode. Click on door. Nothing happens.

#### Steps to reproduce
Use a screwdriver on the hacking multitool to engage Hack Mode. Click on door.

#### Additional info:
master - 2020-06-13 
edd7803517b2dcdc8f9192ce6b6e0e8bc0708c4f

**Comment by Atermonera** [comment] 2020-06-21 22:13
Duplicate of #6943

**Closed by Atermonera** 2020-06-21 22:13 UTC
