### ISSUE TITLE
Teshari Listen In

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2949] opened 2017-01-22 05:09 UTC
#### Brief description of the issue
Teshari Listen in distance is weird
#### What you expected to happen
To be able to hear further and have a accurate measure of how far something is
#### What actually happened
A maintenance drone two tiles away is listed as far away
#### Steps to reproduce
Be a Teshari
Listen in
Drone or something else two tiles away is listed as far away
#### Additional info:
 - **Server Revision**:master - 2017-01-18
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2017-01-22 08:04
The distance description is generated in the switch [here](https://github.com/PolarisSS13/Polaris/blob/73bbe1355e99a17c79caba247d6e43f634a76189/code/modules/mob/living/carbon/human/human_helpers.dm#L123).

**Comment by SilverTalismen** [comment] 2017-01-23 03:19
Teshari also cannot hear through walls, only through line of sight, which makes it useless

**Comment by Anewbe** [comment] 2017-02-25 01:08
Just retested this, was working as intended. Closing this issue.

**Closed by Anewbe** 2017-02-25 01:08 UTC
Labels: Bug
