### ISSUE TITLE
Unusual turf/icon behavior when creating latticework on the outpost.

### ISSUE THREAD

**Issue by Earthcrusher** [PolarisSS13/Polaris#535] opened 2015-12-11 20:29 UTC
We created a chamber on the very edge of the outpost. The lattices we set down inherited the asteroid turf beneath them, even when set on space turfs. Take note of the "edge" tiles still present, even when mixed in with other asteroid tiles.

![9/11 was an inside job](http://i.imgur.com/j8mP01e.png)

**Comment by Neerti** [comment] 2015-12-11 20:32
Duplicate of #533

**Closed by Neerti** 2015-12-11 20:32 UTC
