### ISSUE TITLE
You can't fix built FBPs

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1841] opened 2016-06-01 05:31 UTC
#### Brief description of the issue
Tin. You also cannot use the cyborg analyzers on them.
#### What you expected to happen
You fix them.
#### What actually happened
You don't.
#### Steps to reproduce
Try all of the above.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by TableTurning** [comment] 2016-06-01 07:48
Self repair seemed to work, along with getting fixed by a science borg.

**Comment by Arokha** [comment] 2016-06-01 20:26
The proc for repairing oneself vs someone else repairing you are the same. Are you sure it was the right tool and stuff? Works for me.

>Prosthetics Fabricator pings, indicating that FBP torso (M) is complete.
Unknown has been battered in the robotic upper body with crowbar by Wynter Zaun!
You switch the the upgraded welding tool on.
Wynter Zaun patches some dents on Unknown's robotic upper body with the upgraded welding tool.
Your eyes burn.
You switch the upgraded welding tool off.

**Comment by Searif** [comment] 2016-06-02 00:47
The problem comes from placing them on the operating table, you can't do anything with them on the operating table.

**Comment by Spookerton** [comment] 2016-06-02 01:17
So the actual issue here is that either surgery tries to use things in surgery steps before checking if they have another thing they should do, or doesn't check afterward if the item has no valid surgery step. IDC to look up which order is appropriate.

The result is that WHEN AN FBP IS PRONE ON A VALID SURGERY SURFACE:
It cannot have surface repairs performed on it.
The cyborg analyzer does not do cyborg analyzer things.
Other non-surgery FBP item interactions also don't work.

Under other circumstances, these things work as expected.

**Comment by Arokha** [comment] 2016-06-02 01:19
This is a result of surgery changes ONLY allowing surgery-useful items on help intent. This is true for normal surgery too. You cannot use a syringe or health analyzer on a person on an operating table. This is not specific to FBPs. There was an issue a bit ago about whether or not people would rather accidentally attack people during surgery, or have limited interactions, and the latter won out.

The way to fix that would be to undo those changes, but I’m unsure if that’s desirable.

**Comment by Arokha** [comment] 2016-06-02 01:19
This is a duplicate of #1849

**Closed** 2016-06-02 16:25 UTC
Labels: Duplicate Bug Report
