### ISSUE TITLE
Emagged / Hacked borgs are not lockdown resistant anymore.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#4031] opened 2017-10-07 05:47 UTC
#### Brief description of the issue
Emagging or hacking a cyborg via console as a rogue AI does not make the borg lockdown-resistant.
#### What you expected to happen
Cyborg to get a message saying 'Someone tried locking you down', and retain the ability to act.
#### What actually happened
Cyborg is locked down, making it completely useless, and likely a threat later, to you. (The emagger.)
#### Steps to reproduce
-Emag a cyborg, or hack your cyborg as an insane rogue AI.
-Go to the RD's console, build one yourself, or get a laptop with RD+ ID access and mulah.
-Enable the borg's lockdown.
#### Additional info:
 - **Server Revision**: ccd90031fa4d2121d64ea85e904af61070f10f67 
 - **Anything else you may wish to add** To my knowledge and experience, emagged / hacked borgs were unable to be locked down until some time ago. May have even been Bay-old and no one abused it until recently. **This being a thing means an emagged borg is useless the moment someone finds out something's funky, and has any know-how about using/getting to the console.  Which will likely be quickly if you have them do something like kidnap someone, break something, or anything along those lines on decent-pop. This is especially detrimental considering traitor AI's and off-station antagonists. Emags take 25% of your telecrystals and aren't a guaranteed hack on borgs, and borgs are largely the only 'hands' a rogue AI has to do anything at this time.**

**Comment by Magneld** [comment] 2017-10-07 05:57
This is not ideal. If you want the bad robot to stop being bad you should put in some actual effort and go beat it up. Screwing over a traitor out of their spent TCs and effort put in catching the bot to begin with is one thing but this makes traitor AIs scary for.. about five minutes and then its extended for everyone except engineers busting into the core.

**Comment by Atermonera** [comment] 2017-10-17 05:57
Duplicate of #1245 ?

**Comment by Magneld** [comment] 2017-10-17 06:25
Nah it was a problem ages ago, got fixed, now its a problem again semi recently.

**Comment by Atermonera** [comment] 2017-10-17 06:50
Sooooo the old one should be closed

**Comment by Atermonera** [comment] 2017-11-01 03:01
Currently only applies to emagged borgs, appears to have been fixed for traitorborgs

**Comment by Cameron653** [comment] 2017-11-26 18:10
I believe https://github.com/PolarisSS13/Polaris/pull/4317 addressed this?

**Closed** 2017-11-26 18:51 UTC
