### ISSUE TITLE
Forensics swabs cannot be used on Blood

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1253] opened 2016-03-26 02:36 UTC
#### Brief description of the issue

The forensics swabs cannot be used on blood. However, they work on gibs, bloody footprints, and DRIED bloody footprints.
#### What you expected to happen

For the blood to be swabbed.
#### What actually happened

The blood has been hit by Daniel Wilson with the swab kit.
#### Steps to reproduce

Get swabs.
Find a pool of untouched blood.
Try to swab it.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-03-23
a9ad84da4bea4a9ea90030d54c8183b0672be08c 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

![](https://i.gyazo.com/2f89d9547e31876b3892de7756d4dfdc.png)

**Comment by Atermonera** [comment] 2017-11-01 06:37
Duplicate of #1168, can probably be closed

**Closed** 2017-11-01 06:38 UTC
Labels: Needs Retesting
