### ISSUE TITLE
Choosing a synth brain/head while not a synth.

### ISSUE THREAD

**Issue by Cameron653** [PolarisSS13/Polaris#4005] opened 2017-10-01 19:23 UTC
#### Brief description of the issue
You can choose a synth brain while not a synth, along with other fun bugs.
#### What you expected to happen
Be unable to choose synth head/told I can't have a synth brain without being a synth
#### What actually happened
Was able to do so.
#### Steps to reproduce
ROBOTIC BRAIN:
1. Open up a character slot https://i.imgur.com/K52Wlaq.png
2. Go to "Limbs: Adjust", go to full body, Prosthesis, and select. https://i.imgur.com/sgQSGJP.png
3. Open "internal organs" and select brain, leave this window open: https://i.imgur.com/dUnz2Ot.png
4. Click "Reset" for limbs https://i.imgur.com/T1YodVQ.png
5. Choose whatever brain type you want: https://i.imgur.com/AyR5Mb1.png
6. Go in game, chop your head off & see what occurs: https://i.imgur.com/VVIJM8k.png

ROBOTIC HEAD:
1. Same steps as steps 1-3 above. https://i.imgur.com/VCL3g2V.png
4. Click "Limbs: Adjust" and then click "Head" https://i.imgur.com/eV9xxND.png
5. Click "OK" to get to the manufacturer select https://i.imgur.com/0TxmAik.png
6. Click "Reset" for limbs https://i.imgur.com/QFauGL4.png
7. Choose your head. https://i.imgur.com/GIb8scm.png
8. Join in game. https://i.imgur.com/wQeeuZE.png

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab. 9acc8a5d2c9479c4f06fcb0d99c76ff2db9ab6c1 (The current, most recent one)
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
The code just needs more checks, but I can't be arsed to do it.

**Comment by Anewbe** [comment] 2017-10-01 19:28
Pretty sure this is a known bug.

**Comment by Cameron653** [comment] 2017-10-01 19:31
As far as I could see when I checked, there was #679 but that was from 2015 and isn't he same issue as this, as the mechanical organs are removed upon resetting, but this is an entirely different bug.

**Comment by Atermonera** [comment] 2017-11-01 06:20
Duplicate of #1965

**Closed** 2017-12-30 05:54 UTC
Labels: Duplicate Bug Report
