### ISSUE TITLE
Pumpkins

### ISSUE THREAD

**Issue by ApolloDensin** [PolarisSS13/Polaris#3934] opened 2017-09-24 18:28 UTC
#### Brief description of the issue
Pumpkins are green and look like a watermelon, but turn into a pumpkin shape and color when carved
#### What you expected to happen
For ripe pumpkins to look the correct shape
#### What actually happened
they look like a watermelon
#### Steps to reproduce
Grow a pumpkin and then harvest them
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment] 2017-09-24 18:29
Known thing, the way hydroponics works might make this unfixable.

**Comment by Atermonera** [comment] 2017-11-01 06:36
Duplicate of #1203

**Closed** 2017-11-01 06:38 UTC
