### ISSUE TITLE
Disposal pipes appear on top of tiles

### ISSUE THREAD

**Issue by Noreaus** [PolarisSS13/Polaris#333] opened 2015-11-28 16:47 UTC
After laying disposal pipes, when tiles are replaced on top of them, the tiles appear below the pipes.

As so -

![pipe3](https://cloud.githubusercontent.com/assets/5178371/11452924/ac6ac50c-95ef-11e5-8e90-6138f65abbc7.PNG)

**Comment by EmperorJon** [comment] 2015-11-28 17:32
Duplicate of #291.

**Closed** 2015-11-29 12:02 UTC
Labels: Duplicate Bug Report
