### ISSUE TITLE
Body temperature does not fall after burning.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5759] opened 2018-12-05 02:45 UTC
#### Brief description of the issue
I reported this ages ago, and apparently it was due to be fixed by a cold rewrite. It doesn't look like this rewrite is happening. (Or at least not soon.)

When you are set on fire, your body temp goes all the way up. It does not drop again when the fire goes out.

This means that being set on fire for more than one or two seconds is death to anyone not in an atmospherics voidsuit, or firesuit.

There are a tonne more fire weapons now, fuelrods, flamethrowers, incendiary guns, planetside fire hivebots.

#### What you expected to happen
The fire to go out, the burn damage to stop.

#### What actually happened
The fire goes out, the burn damage continues until the body temperature falls. Damage even continues after the fire is out, and the person has died.

#### Steps to reproduce
Set yourself on fire.
Extinguish yourself.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2018-12-11 00:19
Duplicate of #5096

**Comment by Neerti** [comment] 2018-12-11 00:20
As a note, the hivebots don't use 'real' fire but use a modifier-based damage over time effect that has the appearance of being on fire.

**Comment by Atermonera** [comment] 2018-12-11 00:31
See the other report for what actually happens currently when you get set on fire briefly.

**Closed by Atermonera** 2018-12-11 00:31 UTC
Labels: Duplicate Bug Report
