### ISSUE TITLE
Powersinks do not explode

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#593] opened 2015-12-16 02:42 UTC
Have noticed on a couple occasions powersinks will continue to draw power but never to the point where they'll explode. They do not even get to the screeching stage. Unsure of this is a bug or a feature of power sinks.

**Comment by Hubblenaut** [comment] 2015-12-16 11:06
Its capacity is 50 times higher than it currently is on bay master, as intended to incorporate the high output of the supermatter engine. It might just be that it did not hit that capacity yet when you checked on it.

power_drawn will tell you exactly how much power has already been syphoned. If that raises over 5 000 MJ, boom.

**Comment by PsiOmegaDelta** [comment] 2015-12-16 12:32
And if memory serves, it also lose charge over time (even while connected) making it take even longer to cap out.

**Comment by Datraen** [comment] 2015-12-21 08:25
So powersinks need to be taken down a notch as far as capacity is concerned.

**Comment by Anewbe** [comment] 2016-09-17 06:13
#2482 might finally fix this

**Comment by Anewbe** [comment] 2016-10-06 23:20
It goes boom now, closing.

**Closed by Anewbe** 2016-10-06 23:20 UTC
Labels: Bug, Easy Fix, Priority: Low
