### ISSUE TITLE
F6 > Player Panel > Search feature not working

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#427] opened 2015-12-05 02:12 UTC
See title.

**Comment by EmperorJon** [comment] 2015-12-05 02:16
Please at least do a rudimentary search before reporting... :p

Duplicate of #341.

**Closed by EmperorJon** 2015-12-05 02:16 UTC

**Comment by zaredman** [comment] 2015-12-05 02:18
YOU KNOW WHAT I LOOKED OK

I DIDNT LOOK HARD BUT I LOOKED

GIVE ME THAT AT LEAST

**Comment by EmperorJon** [comment] 2015-12-05 02:18
Well maybe you should have looked harder. Using the search function. Not the one in the player panel, though, that's broken. Someone should report that.
