### ISSUE TITLE
Horse mask can't be melted via acid

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1124] opened 2016-03-06 06:06 UTC
#### Brief description of the issue
The Horse mask is coded to be destroyed when the face is splashed with sacid/pacid, this doesn't happen.
#### What you expected to happen
For the mask to dissolve.
#### What actually happened
The mask didn't dissolve.
#### Steps to reproduce
1. Get a wizard, Harry.
2. Get the horse mask spell.
3. Inflict the spell on someone.
4. Dump Pacid/Sacid on their face.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-04
d66ffcdbbfa6ddf9da3517570615b81ffe2ae8ee 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Logs:
* ATTACK: X (X) splashed Y (Y) with large beaker. * * Reagents: pacid (90)sacid (30) (INTENT: DISARM) (JMP)
* Y has been splashed with something by X!
* Your the horse head mask protects you from the acid.
* Your the horse head mask protects you from the acid.

*Why the long face?*

**Comment by Kelenius** [comment] 2016-03-06 07:28
Just remooooooooove the spell and be done with it.

**Comment by Mark9013100** [comment] 2016-03-06 07:33
That's no fun.

**Comment by Atermonera** [comment] 2016-03-07 07:23
Duplicate of #452

**Closed** 2016-03-12 16:23 UTC
Labels: Duplicate Bug Report
