### ISSUE TITLE
Butchered spiders briefly appear as a monkey

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#4642] opened 2018-01-26 09:09 UTC
#### Brief description of the issue
Title
#### What you expected to happen
Not title
#### What actually happened
title
#### Steps to reproduce
Butcher a spider
It turns into a monkey then explodes into meat and gibs
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment] 2018-01-26 16:02
I believe this was because the monkey is part of the gib animation? I'd need to fact check it.

**Comment by Anewbe** [comment] 2018-01-26 21:48
Correct

**Comment by Atermonera** [comment] 2018-01-27 00:57
Duplicate of #2449

**Closed** 2018-01-27 00:58 UTC
Labels: Duplicate Bug Report
