### ISSUE TITLE
Antag door hacking tool doesn't work

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7198] opened 2020-05-19 12:23 UTC
#### Brief description of the issue
The door hacking tool does not hack doors, no matter how much you screwdriver it
#### What you expected to happen
for doors to be hacked
#### What actually happened
a broken tool ruining my antag objectives
#### Steps to reproduce
get the door hacking tool, screwdriver it, be dissapointed.
#### Additional info:
 - **Server Revision**:
2020-05-12

**Comment by FenodyreeAv** [comment] 2020-05-19 13:08
Screwdrivering it does toggle the must_hack variable, but then it doesn't actually do anything.
Probably something to do with #6835 or #6810

**Comment by Greenjoe12345** [comment] 2020-05-19 13:48
That's a different kind of hacking though
The door hacker gives you a AI style door interface

**Comment by FenodyreeAv** [comment] 2020-05-19 13:55
It touched the way that clicking doors is handled, and it's the most recent thing to do so.

**Comment by Atermonera** [comment] 2020-06-21 22:13
Duplicate of #6943

**Closed by Atermonera** 2020-06-21 22:13 UTC
