### ISSUE TITLE
Unable to add coolant to spectrometer

### ISSUE THREAD

**Issue by Crackers5** [PolarisSS13/Polaris#1874] opened 2016-06-04 20:53 UTC
#### Brief description of the issue
When attempting to add coolant to the radiocarbon spectrometer, spectrometer does not fill, bucket does not empty.

#### What you expected to happen
Coolant inside bucket to be transferred to spectrometer

#### What actually happened
Message saying coolant added, but nothing actually happening

#### Steps to reproduce
Fill bucket with coolant, attempt to add coolant to spectrometer

#### Additional info:
 - **Server Revision**: master - 2016-06-02
 - **Anything else you may wish to add**  http://puu.sh/pgOWx.png

**Comment by SinTwo** [comment] 2016-08-03 15:55
duplicate of #2049. Closing as #2049 has more info about the problem.

**Closed by SinTwo** 2016-08-03 15:55 UTC
