### ISSUE TITLE
ERT issues

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#788] opened 2016-01-15 23:13 UTC
1.) When changing genders as an ERT op, the sprite will stay as the male sprite.

2.) ERT don't spawn with a team leader, they did previously however.

**Comment by Neerti** [comment] 2016-01-15 23:38
2. is intentional iirc.

**Comment by EmperorJon** [comment] 2016-01-17 03:00
1 is duplicate of https://github.com/PolarisSS13/Polaris/issues/498.
Closing.

Also please don't report multiple issues in one ticket if possible.

**Closed by EmperorJon** 2016-01-17 03:00 UTC
Labels: Bug, Duplicate Bug Report
