### ISSUE TITLE
Research Borgs unable to work in New-Xenobiology

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#3546] opened 2017-06-25 22:08 UTC
#### Brief description of the issue
Research borgs, before the xenobio change, were able to xenobiology, core holding and all. Now, they cannot hold cores in their gripper, hopefully, due to oversight and forgetfulness rather than active ignoring.
#### What you expected to happen
Sci-Gripper to be able to hold a slime core to shove it into the growth apparatus or grinder.
#### What actually happened
Sci-gripper cannot hold a slime core.
#### Steps to reproduce
Be a research borg, dispense a slime core from the fridge.
Try to grip the core. Realize you can't.
Look longingly at the growth apparatus while a sad song of lost history plays in the background.
#### Additional info:
 - **Server Revision**: 6ddd39490008945f2f73a2cd91e86a11c10b78d7 
 - **Anything else you may wish to add**: Due to the fact Research borgs were meant to be able to do xenobiology (and were able to do it minus phoron grinding) in the first place, they'd also need a slime-baton and analyzer to be able to do it with this new system. I'm assuming this fact was forgotten by the person who made new-xenobio.

**Comment by Atermonera** [comment] 2017-06-26 02:01
Partial duplicate of #349

**Comment by Mechoid** [comment] 2017-06-27 00:02
Slime extracts aren't used anymore, they were replaced with the incredibly boring cores that you grind up. Which weren't added to the gripper's list for some reason.

**Comment by Atermonera** [comment] 2017-06-28 05:10
The missing functionality remains the same, seeing as old xenobio was completely replaced with xenobio2

**Closed** 2017-07-04 21:51 UTC
