### ISSUE TITLE
Destructive analyzer does not 'come apart' when crowbarred

### ISSUE THREAD

**Issue by thezblah** [PolarisSS13/Polaris#3547] opened 2017-06-26 16:34 UTC
It just spits out a frame and remains whole, it can be repeatedly crowbarred for many, many frames. https://i.gyazo.com/4e12fdcebf607099d474ff3992d5bed1.png

**Comment by Atermonera** [comment] 2017-07-01 19:58
Unable to reproduce: [https://puu.sh/wz9ZY/d4bd605b3a.mp4](https://puu.sh/wz9ZY/d4bd605b3a.mp4)

Had anything special happened to the analyzer before you tried to deconstruct it?

**Comment by FenodyreeAv** [comment] 2017-07-01 20:39
I reported this a long time ago. Might have something to do with using the analyser to deconstruct something first, as you'll never disassemble it until you've got better tech.

**Comment by SpadesNeil** [comment] 2017-07-21 19:17
We're having a similar bug. Not sure if related.

https://github.com/VOREStation/VOREStation/issues/1883

**Comment by Atermonera** [comment] 2017-11-01 05:50
This is actually a duplicate of #3404

**Closed** 2017-12-30 06:04 UTC
Labels: Duplicate Bug Report
