### ISSUE TITLE
Solar SMES don't charge

### ISSUE THREAD

**Issue by Bromuzl** [PolarisSS13/Polaris#479] opened 2015-12-08 13:50 UTC
Discovered while wiring solar as drone this morning.
Wired solars as previously would, SMES remained red even during peak stellar orientation.
Disconnected  and reconnected wires to SMES and terminal.
Disassembled and reassembled terminal, SMES and terminal after.
Would not charge if set to anything greater than 0w input.

**Comment by zaredman** [comment] 2015-12-08 17:53
Was this a one-time thing or multi-round?

**Comment by NortonDK** [comment] 2015-12-08 19:48
As an engineer i've had no problems with getting solars and solars SMESs to work. Only tried the one west of engineering though.

**Comment by Dibasic** [comment] 2015-12-13 10:22
Will test tomorrow

**Comment by Dibasic** [comment] 2015-12-13 10:51
Hi, I reproduced this just by setting up the solars as normal: http://puu.sh/lTOtJ/3de77ab348.jpg

In this screenshot:
Solars are producing 99,000 watts. Engine is producing 500,000 watts. Yellow (solar) wire has 599,000 watts. Red (main grid) wire has 599,000 watts. SMES is set to 250,000 watts in, input auto, is not charging. Doesn't charge. Seems like the solars are wired into the grid-- but they're not, they're wired into the terminal, which is connected to the SMES, which isn't on the grid.

Now I cut a wire leading into the terminal: http://puu.sh/lTOC6/329011c281.jpg
Still wired into the grid, apparently. Cut the wire leading into the APC, still on the grid. Cut the wire leading into the solar control PC, main grid defaults to 500,000 watts (the engine's output setting.)

So ?????

**Comment by Dibasic** [comment] 2015-12-13 10:52
fixed the wire into the computer. left the apc and smes disconnected. solars themselves now have 500kw of power.

**Comment by GinjaNinja32** [comment] 2015-12-13 20:48
How much of that 599kW was being used in the rest of the station?

**Comment by Dibasic** [comment] 2015-12-14 14:18
@GinjaNinja32 probably all of it

**Comment by GinjaNinja32** [comment] 2015-12-14 16:55
Then the SMES won't charge because the rest of the station is using the power?

**Comment by Dibasic** [comment] 2015-12-14 17:32
@GinjaNinja32 The SMES should charge from its input terminal, which is attached to the solar panels. The problem here is that the input (yellow, solar panel) wire is connected to the output (red, station power grid) wire somehow through that solar panel control console.

**Comment by GinjaNinja32** [comment] 2015-12-14 17:36
My guess is those two curved sections are connecting to each other.

**Comment by Zokkie** [comment] 2016-01-08 17:32
I can confirm what GinjaNinja32 said. Those two curved sections cause the problem I think. Only kept the one intact leading to the solar SMES and the solar power was going through it as it should. When I installed the other curved part back it would go straight to the main grid again. 

I tested this at the aft port solars.

**Comment by nczempin** [comment] 2016-01-09 15:43
I can confirm that the two cables are interfering with each other. I connected the yellow wire differently and things work as expected (yellow cable from solar charges SMES, red cable is main grid, output from SMES goes to main grid).

![screenshot 2016-01-09 16 33 29_cropped](https://cloud.githubusercontent.com/assets/1781405/12216842/35aaff1a-b6ef-11e5-9f5b-bb83d81c96ec.png)


Note that the issue is not that the SMES isn't charging (so it should be retitled), it charges fine when there is sufficient power on the main grid and the output is off, which is expected behaviour if the SMES input is connected to the main. It should be "solar connected to the main grid" or perhaps more generally "visually unconnected wires actually connected" or something like that.

I have only checked this on the aft port (South West) solar SMES, I will check
1) the other solars
2) if it is a general problem with curved wires actually touching. (it could be that the curving is visual only, and that in fact they are connected in the middle).

In the meantime, there is a workaround: connect the wires on the map like the screenshot shows. This can either be done by the engineers IG or by a map editor.

**Comment by nczempin** [comment] 2016-01-09 16:10
On BS12, this is wired differently, with the wires not going through the same tile.
![screenshot 2016-01-09 17 10 10_cropped](https://cloud.githubusercontent.com/assets/1781405/12217012/e5ef2be0-b6f3-11e5-8c36-2fc9956363b3.png)

**Comment by nczempin** [comment] 2016-01-09 16:35
The other panel SMESes on Polaris are wired correctly, thus should work properly. It would be nice for someone to check IG.

As I said before, this either needs to be changed in the map or it can be used IG for e. g. a Chief Engineer to send a technician to figure out what's wrong. Not sure how quickly that gets old.

**Comment by nczempin** [comment] 2016-01-09 20:17
All the solars charged just fine, including the miswired aft port one, after I had rewired it according to the screenshot.

So there are 3 options:
1) close this issue, the wiring will be fixed in-game
2) rename this issue to something like "wiring on port aft solar SMES needs to be fixed in the map"
3) I guess there could be a dependency to a BS12 issue that apparently fixed the curved-wiring-in-one-tile issue.https://github.com/Baystation12/Baystation12/pull/6651, but it would probably be more involved than 1) or 2).

**Comment by GinjaNinja32** [comment] 2016-01-10 16:30
Caused by https://github.com/Baystation12/Baystation12/issues/11955. Cutting and replacing either of the wires on the same turf will fix the issue.

**Comment by Bromuzl** [comment] 2016-01-10 20:42
/proc/makepowernets() (called at startup) is the culprit, you can verify by laying out cables manually and then debug-calling this proc
Sent from my T-Mobile 4G LTE Device-------- Original message --------From: GinjaNinja32 <notifications@github.com> Date: 1/10/2016  8:30 AM  (GMT-08:00) To: PolarisSS13/Polaris <Polaris@noreply.github.com> Cc: Bromuzl <grizly007@gmail.com> Subject: Re: [Polaris] Solar SMES don't charge (#479) 
Caused by Baystation12/Baystation12#11955. Cutting and replacing either of the wires on the same turf will fix the issue.

**Comment by GinjaNinja32** [comment] 2016-01-10 22:13
true fix exists in https://github.com/Baystation12/Baystation12/pull/11958

**Closed** 2016-01-11 17:58 UTC
Labels: Needs Testing
