### ISSUE TITLE
Duct-tape, Paper & Cameras

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#5609] opened 2018-09-26 19:49 UTC
#### Brief description of the issue
Duct-taping Paper over Camera's to block their view basically permanently disables the camera as you can't remove the paper after.
#### What you expected to happen
To be able to remove the piece of paper taped to the camera after
#### What actually happened
Stuck forever, immune to any tool or device.
#### Additional info:
 - **Server Revision**: master - 2018-09-23
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2018-10-16 03:48
Duplicate of #2642

**Closed** 2018-10-16 03:48 UTC
Labels: Duplicate Bug Report
