### ISSUE TITLE
Teshari FBPs putting on hardsuits overheat immediately

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7252] opened 2020-05-28 16:53 UTC
#### Brief description of the issue
Hardsuit suit coolers do not work until the suit is fully deployed. This means that while the suit is deploying you take 80ish burn damage.

#### What you expected to happen
To not burn to death.

#### What actually happened
Burning to death.

#### Steps to reproduce
Be a Teshari FBP, put on a hardsuit.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2020-06-21 22:19
Duplicate of #6345

**Closed by Atermonera** 2020-06-21 22:19 UTC
Labels: Duplicate Bug Report
