### ISSUE TITLE
Whispers fuck with formatting

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#3099] opened 2017-03-17 23:20 UTC
#### Brief description of the issue
The asterisks in whispers are causing things to be randomly bolded.

#### What you expected to happen
For them to be displayed as they were before.

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/14942479/24066180/2f82d030-0b68-11e7-9dd6-a682f088b8f6.png)

#### Steps to reproduce
Have someone whisper while almost in earshot.

#### Additional info:
 - **Server Revision**: Server revision: release - 2017-03-14
89af151c970380f16f994bba6387fc7ce1f2e883

**Comment by Neerti** [comment] 2017-03-17 23:22
Think this is a duplicate of #3084.  Porting #3087 should fix it.

**Comment by Screemonster** [comment] 2017-03-17 23:33
Aha, that'd be it. Didn't check closed issues.

**Closed** 2017-03-17 23:33 UTC
