### ISSUE TITLE
FBP bloodied sprites have their species' blood appear on them instead of black/oil when attacked

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#949] opened 2016-02-09 23:59 UTC

**Comment by Zuhayr** [comment] 2016-02-09 23:59
God dammit I thought I fixed this.

**Comment by Anewbe** [comment] 2016-06-28 00:27
Believe this was fixed by the Terminator Update.

**Comment by Atermonera** [comment] 2017-07-19 22:39
Unable to reproduce:
[https://puu.sh/wNXRB/521cf71eed.mp4](https://puu.sh/wNXRB/521cf71eed.mp4)
[https://puu.sh/wNXXL/36ab0eeba3.mp4](https://puu.sh/wNXXL/36ab0eeba3.mp4)

**Comment by Anewbe** [comment] 2017-09-23 19:57
Seems to be fixed in most recent build, closing.

**Closed by Anewbe** 2017-09-23 19:57 UTC
Labels: Bug, Needs Retesting
