### ISSUE TITLE
cannot cut pizzas with knives

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#745] opened 2016-01-08 19:53 UTC
because you can eat with knives now, steel knives from the kitchen vending machine will act like forks with a pizza instead of cutting it

**Comment by Datraen** [comment] 2016-01-11 04:04
Has to do with how kitchen utensils are in the code. I could add a check to see if the item is slicable or not and if it's a slicing utensil, in the case of a few other knives.

**Comment by Datraen** [comment] 2016-01-12 04:09
Forgive the delay, not forgotten, I've just been busy with work.

**Comment by Zuhayr** [comment] 2016-01-13 13:12
Dupe of #270

**Closed by Zuhayr** 2016-01-13 13:12 UTC
