### ISSUE TITLE
Delivery Grenade Still Doesn't Work

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1273] opened 2016-03-28 04:05 UTC
#### Brief description of the issue
I threw it, it didn't work.
#### What you expected to happen
Manhacks to tear apart my enemies.
#### What actually happened
NOTHING.
#### Steps to reproduce
Throw grenade. Nothing goes on.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-27
ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Magneld** [comment] 2016-03-28 19:42
Admin spawned Manhack grenades work as intended so for now we'll try and spawn those in at the start of heist rounds for you. As for the existing grenade its probably a mapping mistake as I know a blank version exists so odds are thats what you guys ended up with.

**Comment by EmperorJon** [comment] 2016-04-03 18:47
Fixed in #1332

**Closed by EmperorJon** 2016-04-03 18:47 UTC
Labels: Map Change / Issue, Priority: Low
