### ISSUE TITLE
Able to attempt to pull off people's gear while stunned.

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4244] opened 2017-11-08 01:07 UTC
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2017-11-08 03:38
Duplicate of #1977

**Comment by Atermonera** [comment] 2017-11-15 22:32
Missed this when I put up #4265 but it should've been closed by it

**Closed** 2017-11-15 22:33 UTC
