### ISSUE TITLE
Robotic limbs behave as normal ones RE fixing damage

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#422] opened 2015-12-04 17:36 UTC
BAsically, welding tools and cable coils do not work in robotic arm/leg repair, bruisepacks and ointment work instead. The "wounds" can bleed and get infected. This is un-ideal, though funny.

**Comment by Techhead0** [comment] 2015-12-21 23:23
For those interested, this is a duplicate of https://github.com/Baystation12/Baystation12/issues/10444.

**Closed** 2016-01-13 13:09 UTC
Labels: Bug
