### ISSUE TITLE
Randomise Appearance in Charsetup produces an error

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1227] opened 2016-03-22 22:29 UTC
#### Brief description of the issue
Clicking the "R" beside Body in charsetup causes an error, and does not randomise appearance.
#### What you expected to happen
Appearance to be randomised.
#### What actually happened
Appearenace was not ramondised. Error below:

runtime error: Cannot execute null.get organ().
proc name: randomize appearance for (/datum/preferences/proc/randomize_appearance_for)
  source file: preferences_setup.dm,21
  usr: Yoshax (/mob/new_player)
  src: /datum/preferences (/datum/preferences)
  usr.loc: null
  call stack:
/datum/preferences (/datum/preferences): randomize appearance for(null)
Body (/datum/category_item/player_setup_item/general/body): OnTopic("src=\[0x21004445];random=1", /list (/list), Yoshax (/mob/new_player))
Body (/datum/category_item/player_setup_item/general/body): Topic("src=\[0x21004445];random=1", /list (/list))
Yoshax (/client): Topic("src=\[0x21004445];random=1", /list (/list), Body (/datum/category_item/player_setup_item/general/body))
Yoshax (/client): Topic("src=\[0x21004445];random=1", /list (/list), Body (/datum/category_item/player_setup_item/general/body))
#### Steps to reproduce
Hit the "R" button in charsetup.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
https://github.com/PolarisSS13/Polaris/commit/7dfcbcbf3c47187c28edfbf3389ed2454b1126c1
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment] 2016-03-24 14:14
Suspect this is a duplicate of good old #369

**Comment by PsiOmegaDelta** [comment] 2016-03-24 18:20
I wonder if there's a spawn somewhere in the species setup/organ creation code.

**Closed** 2016-05-19 22:18 UTC
Labels: Duplicate Bug Report
