### ISSUE TITLE
Vey-Med FBPs show up as Unbranded in setup preview

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#5414] opened 2018-07-14 23:37 UTC
#### Brief description of the issue
Tin.

#### What you expected to happen
My Vey-wearing character to look humanish

#### What actually happened
https://cdn.discordapp.com/attachments/182550163263324160/467836673066139668/unknown.png

#### Steps to reproduce
Char setup
Adjust limbs
Full Body
Vey-Medical
Cri Every Time

**Comment by Belsima** [comment] 2018-07-15 00:09
Duplicate of #4438

**Comment by elgeonmb** [comment] 2018-07-15 00:37
I thought that was fixed

**Comment by Atermonera** [comment] 2018-07-15 06:59
Haven't seen anyone complain about it recently besides this, but I am unaware of any fixes or attempts at fixing it that have transpired since that report was determined to be a byond bug, to do with opening char setup before initializations were complete

**Closed by Atermonera** 2018-07-15 06:59 UTC
Labels: Duplicate Bug Report
