### ISSUE TITLE
Reset Slot button does nothing

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#3223] opened 2017-04-04 14:49 UTC
#### Brief description of the issue
Reset Slot button does nothing
#### What you expected to happen
The slot to be reset to default
#### What actually happened
Nothing
#### Steps to reproduce
Open a character slot, hit the reset button, hit yes.

**Comment by Atermonera** [comment] 2017-04-04 17:52
Duplicate of #2963

**Closed** 2017-04-04 19:25 UTC
Labels: Duplicate Bug Report
