### ISSUE TITLE
Bolting doors disallows synthetic interaction.

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#409] opened 2015-12-03 22:17 UTC
When bolted, doors prevent access to their nanoui interfaces.
Unbolting the door allows normal interface use.
Ctrl/shift/alt click interaction works normally.
http://i.imgur.com/pUQRgL5.png

**Comment by EmperorJon** [comment] 2015-12-03 22:53
Caused by #359 attempting to fix #328. Runtime is now thrown when synths use hotkeys to act on doors but they appear to work. The nanoUI now works. Clearly it's all still messed up and needs to be investigated. Mostly my fault.

**Comment by Sligneris** [comment] 2015-12-04 17:24
This also appears to be the case with ID scan being disabled.

**Comment by PsiOmegaDelta** [comment] 2015-12-04 18:24
See https://github.com/Baystation12/Baystation12/pull/11589.

**Comment by EmperorJon** [comment] 2015-12-04 19:04
Merged this issue. Bolting no longer breaks everything. Still a topic runtime being thrown when using hotkeys. Example error below:


runtime error: Cannot execute null.Topic().
proc name: Topic (/obj/Topic)
  source file: objs.dm,23
  usr: NCH (/mob/living/silicon/ai)
  src: AI Upload (/obj/machinery/door/airlock/highsecurity)
  call stack:
AI Upload (/obj/machinery/door/airlock/highsecurity): Topic(AI Upload (/obj/machinery/door/airlock/highsecurity), /list (/list), 1)
AI Upload (/obj/machinery/door/airlock/highsecurity): Topic(AI Upload (/obj/machinery/door/airlock/highsecurity), /list (/list), 1)
AI Upload (/obj/machinery/door/airlock/highsecurity): AIShiftClick(NCH (/mob/living/silicon/ai))
NCH (/mob/living/silicon/ai): ShiftClickOn(AI Upload (/obj/machinery/door/airlock/highsecurity))
NCH (/mob/living/silicon/ai): ClickOn(AI Upload (/obj/machinery/door/airlock/highsecurity), "icon-x=21;icon-y=9;left=1;shif...")
AI Upload (/obj/machinery/door/airlock/highsecurity): Click(the floor (140,172,1) (/turf/simulated/floor/tiled/dark), "mapwindow.map", "icon-x=21;icon-y=9;left=1;shif...")

For some reason we've got a null reference. Not entirely sure where to start working this out, as that's a rather new area to me. Will leave this open for now.

**Closed** 2015-12-04 19:08 UTC
Labels: Bug, Priority: High
