### ISSUE TITLE
Ship Landing Sending You Into Full Orbit

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4740] opened 2018-02-06 11:06 UTC
#### Brief description of the issue

Ship landed on my character and sent him to deck 3.

#### What you expected to happen

I'm not sure. I thought it would kill him when I noticed it coming down towards him. I know in the past it usually creates air blast knocking back.

#### What actually happened

Sent from Outpost to Deck 3 when it hit, sending him into space.

#### Steps to reproduce

I don't know, uh step under a landing ship?

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment] 2018-02-06 18:17
Duplicate of #4670

**Closed by Atermonera** 2018-02-06 18:17 UTC
Labels: Duplicate Bug Report
