### ISSUE TITLE
Hardsuit Mounted energy gun cannot go off stun

### ISSUE THREAD

**Issue by Lorwp** [PolarisSS13/Polaris#639] opened 2015-12-21 08:57 UTC
Whenever i attempt to switch the mode of a Hardsuit mounted energy gun (such as the one on ERT-S hardsuits), it switches the mode twice and forces it to stay on stun.

E.g:
![capture](https://cloud.githubusercontent.com/assets/8052896/11926964/010ee432-a81d-11e5-9367-8e6289b54fab.PNG)

**Comment by Neerti** [comment] 2015-12-21 09:35
Duplicate of #79

**Closed** 2015-12-21 09:35 UTC
Labels: Duplicate Bug Report
