### ISSUE TITLE
Research Borgs cannot attach/insert prosthetic (and flesh, assumedly) organs/limbs.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1998] opened 2016-06-28 20:48 UTC
#### Brief description of the issue

Research cyborgs cannot attach prosthetic limbs or re-insert organs they have removed.
#### What you expected to happen

Research cyborgs could re-attach an FBP's leg or head, for instance if it lost either. Or restart a newly repaired FBP by removing and/or re-inserting its cell or brain.
#### What actually happened

The gripper does nothing. Post-surgery change, it now gives the 'you can't find a use for this' message regarding the gripper itself.
#### Steps to reproduce

Be a research cyborg, saw off an FBP's limb, try to re-attach.
Be a research cyborg, rip out an FBP's cell, try putting it back in.
#### Additional info:
- **Server Revision**: 6374bc2c4c342b53bbf2950b9e792ec7e2084495
- **Anything else you may wish to add**

**Comment by Edwardc120** [comment] 2016-06-29 19:57
Also for gripers the sheet loaders can't load there materials into Protolathes like they can autolathes

**Comment by Anewbe** [comment] 2016-06-29 20:48
Was this working at any point, or has it been broken since the flesh grippers were added?

**Comment by Mechoid** [comment] 2016-06-30 20:03
Robotic limbs functioned beforehand, though they likely ceased once they were made into objects of differing type from normal borg-body limbs. With internal organs/parts like the brain and (For FBP's) the minibattery, it's persisted since the gripper was added.

**Comment by Atermonera** [comment] 2016-12-17 22:54
Unable to reproduce, looks like this's been fixed,

**Comment by Atermonera** [comment] 2016-12-24 06:48
Ok, this should have been closed when #2864 got merged. I'll look into testing it again, just to double check.

**Closed** 2016-12-30 03:44 UTC
Labels: Bug
