### ISSUE TITLE
Body Scanner doesn't show appendicitis

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1474] opened 2016-04-22 08:21 UTC
#### Brief description of the issue:
Even if an appendix is inflamed, it won't show up as inflamed on the body scanner. 

#### What you expected to happen:
For the appendix to show up as inflamed on the body scanner.

#### What actually happened:
The Appendix was reported as healthy, even when it wasn't.

#### Steps to reproduce:
1. Find someone with appendicitis
2. Throw them in the body scanner.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-04-22
134157feb579191f6429c479cb61572b67261971 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment] 2016-04-22 13:50
Duplicate of #1094

**Closed** 2016-04-22 17:46 UTC
Labels: Duplicate Bug Report
