### ISSUE TITLE
Stationbound Synthetics do not understand the native Tesh. Language.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1600] opened 2016-05-08 22:18 UTC
#### Brief description of the issue
AI's and borgs cannot understand Teshari.
#### What you expected to happen
AI's and Borgs to understand the native Teshari language, and for service/clerical borgs to be able to speak it like the other languages.
#### What actually happened
AI's and Borgs cannot understand it. Borgs cannot then speak it when in the correct modules.
#### Steps to reproduce
Be a borg, note languages.
#### Additional info:
 - **Server Revision**:  454cc25cba9d3de5a0a99b7e5586ed34790d4aed 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc): When I asked Zuhayr previously, he stated synths would get the language two weeks after their introduction. After asking Khold approx a week ago, he also ok'd the language being added to synths.

**Comment by Datraen** [comment] 2016-05-09 12:36
Duplicate of #1448

**Closed by Datraen** 2016-05-09 12:36 UTC
Labels: Duplicate Bug Report
